### ISSUE TITLE
Off topic question

### ISSUE THREAD

**Issue by dalb8** [htruong/sophia_oss#1]
Hi, I just submitted the recipe for Sophia to the f-droid.org repository. I set minsdk to 11 according to the description on Google Play.

I would also like to get AOSP Pinyin IME built with Android SDK; I know my way around the SDK fine, but can't figure out the AOSP stuff. If anybody is able to help I'd greatly appreciate it

**Comment by dalb8** [comment]
I got LatinIME to compile, thanks to this repo(not with 4.4 though; only 4.2). I can't get Pinyin IME to build; strange errors with padding etc.

```
[javac] /home/gerry/fdroiddata/build/com.android.inputmethod.pinyin/src/com/android/inputmethod/pinyin/SkbContainer.java:24: error: cannot find symbol
[javac] import android.os.SystemProperties;
[javac]                  ^
[javac]   symbol:   class SystemProperties
[javac]   location: package android.os
[javac] /home/gerry/fdroiddata/build/com.android.inputmethod.pinyin/src/com/android/inputmethod/pinyin/BalloonHint.java:400: error: cannot find symbol
[javac]             int measuredWidth = mPaddingLeft + mPaddingRight;
```

**Comment by htruong** [comment]
The build system is pretty hairy.

I will need to look at it at some point to get it to build and clean up and update it to the latest AOSP upstream.

**Comment by dalb8** [comment]
The Android 4.4 keyboard source code is more or less the same. To compile native parts with ndkr9 though you need to suppress errors, like ndk-build -e "APP_CFLAGS += -w"
